#!/usr/bin/env python
#
# Make a .dockerignore file that only accepts files currently tracked by Git
#
# See https://j.mp/make-dockerignore

from subprocess import check_output as run

with open('.dockerignore','w') as f:
  f.write('# Generated by make-dockerignore.py: https://j.mp/make-dockerignore\n')
  f.write('*\n')
  f.write('!.git\n')
  f.flush()
  [
    f.write(f'!{line}\n')
    for line in
    run(['git','ls-files']).decode().split('\n')
    if line
  ]